/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AutomationWithdrawAndCloseAutomationIxBody
 */
export interface AutomationWithdrawAndCloseAutomationIxBody {

    /**
     * User's wallet address who owns the position.
     *
     * @type {string}
     * @memberof AutomationWithdrawAndCloseAutomationIxBody
     */
    userWallet?: string;

    /**
     * Current user's position address from Meteora.
     *
     * @type {string}
     * @memberof AutomationWithdrawAndCloseAutomationIxBody
     */
    currentPosition?: string;
}
