/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AutomationLimitCloseAutomationIxBody
 */
export interface AutomationLimitCloseAutomationIxBody {

    /**
     * User's wallet address who owns the position.
     *
     * @type {string}
     * @memberof AutomationLimitCloseAutomationIxBody
     */
    userWallet?: string;

    /**
     * Current user's position address from Meteora.
     *
     * @type {string}
     * @memberof AutomationLimitCloseAutomationIxBody
     */
    position?: string;

    /**
     * Minimum bin-id target to close position
     *
     * @type {number}
     * @memberof AutomationLimitCloseAutomationIxBody
     */
    minBinId?: number;

    /**
     * Maximum bin-id target to close position
     *
     * @type {number}
     * @memberof AutomationLimitCloseAutomationIxBody
     */
    maxBinId?: number;
}
