/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AutomationCreatePositionAndDepositAutomationIxBody
 */
export interface AutomationCreatePositionAndDepositAutomationIxBody {

    /**
     * Transaction priority (Default, Low, Medium, High, VeryHigh, UnsafeMax, None)
     *
     * @type {string}
     * @memberof AutomationCreatePositionAndDepositAutomationIxBody
     */
    priority?: string;

    /**
     * Max lamports to consume for priority fee
     *
     * @type {number}
     * @memberof AutomationCreatePositionAndDepositAutomationIxBody
     */
    maxPriorityFee?: number;

    /**
     * Whether to disable computing priority fees. True by default which means it ignores priority parameter
     *
     * @type {boolean}
     * @memberof AutomationCreatePositionAndDepositAutomationIxBody
     */
    disableFeeCompute?: boolean;

    /**
     * Meteora pool address
     *
     * @type {string}
     * @memberof AutomationCreatePositionAndDepositAutomationIxBody
     */
    pool?: string;

    /**
     * User's position from Meteora (See GET /meteora/dlmm/util/positions).
     *
     * @type {string}
     * @memberof AutomationCreatePositionAndDepositAutomationIxBody
     */
    position?: string;

    /**
     * User's wallet address who owns the position.
     *
     * @type {string}
     * @memberof AutomationCreatePositionAndDepositAutomationIxBody
     */
    userWallet?: string;

    /**
     * Lower bin range. Must within active range for request to succeed. (see GET /meteora/dlmm/activeBin) to get active range of your selected pool)
     *
     * @type {number}
     * @memberof AutomationCreatePositionAndDepositAutomationIxBody
     */
    lowerBinRange?: number;

    /**
     * Upper bin range. Must within active range for request to succeed. ((see GET /meteora/dlmm/activeBin) to get active range of your selected pool)
     *
     * @type {number}
     * @memberof AutomationCreatePositionAndDepositAutomationIxBody
     */
    upperBinRange?: number;

    /**
     * X and Y token distribution. At the moment, we support default meteora distribution functions: SPOT, CURVE, BID-ASK
     *
     * @type {string}
     * @memberof AutomationCreatePositionAndDepositAutomationIxBody
     */
    distribution?: string;
}
