/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Balance
 */
export interface Balance {

    /**
     * Amount of the asset.
     *
     * @type {string}
     * @memberof Balance
     */
    amount?: string;

    /**
     * The mint address of the asset.
     *
     * @type {string}
     * @memberof Balance
     */
    mint?: string;
}
