/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface HawksightPoolResponse
 */
export interface HawksightPoolResponse {

    /**
     * @type {string}
     * @memberof HawksightPoolResponse
     */
    address?: string;

    /**
     * @type {number}
     * @memberof HawksightPoolResponse
     */
    apr?: number;

    /**
     * @type {number}
     * @memberof HawksightPoolResponse
     */
    apy?: number;

    /**
     * @type {string}
     * @memberof HawksightPoolResponse
     */
    baseFeePercentage?: string;

    /**
     * @type {number}
     * @memberof HawksightPoolResponse
     */
    binStep?: number;

    /**
     * @type {string}
     * @memberof HawksightPoolResponse
     */
    cumulativeFeeVolume?: string;

    /**
     * @type {string}
     * @memberof HawksightPoolResponse
     */
    cumulativeTradeVolume?: string;

    /**
     * @type {number}
     * @memberof HawksightPoolResponse
     */
    currentPrice?: number;

    /**
     * @type {number}
     * @memberof HawksightPoolResponse
     */
    farmApr?: number;

    /**
     * @type {number}
     * @memberof HawksightPoolResponse
     */
    farmApy?: number;

    /**
     * @type {number}
     * @memberof HawksightPoolResponse
     */
    fees24h?: number;

    /**
     * @type {boolean}
     * @memberof HawksightPoolResponse
     */
    hide?: boolean;

    /**
     * @type {string}
     * @memberof HawksightPoolResponse
     */
    liquidity?: string;

    /**
     * @type {string}
     * @memberof HawksightPoolResponse
     */
    maxFeePercentage?: string;

    /**
     * @type {string}
     * @memberof HawksightPoolResponse
     */
    mintX?: string;

    /**
     * @type {string}
     * @memberof HawksightPoolResponse
     */
    mintY?: string;

    /**
     * @type {string}
     * @memberof HawksightPoolResponse
     */
    name?: string;

    /**
     * @type {string}
     * @memberof HawksightPoolResponse
     */
    protocolFeePercentage?: string;

    /**
     * @type {string}
     * @memberof HawksightPoolResponse
     */
    reserveX?: string;

    /**
     * @type {number}
     * @memberof HawksightPoolResponse
     */
    reserveXAmount?: number;

    /**
     * @type {string}
     * @memberof HawksightPoolResponse
     */
    reserveY?: string;

    /**
     * @type {number}
     * @memberof HawksightPoolResponse
     */
    reserveYAmount?: number;

    /**
     * @type {string}
     * @memberof HawksightPoolResponse
     */
    rewardMintX?: string;

    /**
     * @type {string}
     * @memberof HawksightPoolResponse
     */
    rewardMintY?: string;

    /**
     * @type {number}
     * @memberof HawksightPoolResponse
     */
    todayFees?: number;

    /**
     * @type {number}
     * @memberof HawksightPoolResponse
     */
    tradeVolume24h?: number;
}
