/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { HawksightPoolMetrics } from './hawksight-pool-metrics';
import { MeteoraConfig } from './meteora-config';
import { OrcaConfig } from './orca-config';
 /**
 * 
 *
 * @export
 * @interface HawksightPool
 */
export interface HawksightPool {

    /**
     * Unique identifier for the pool.
     *
     * @type {string}
     * @memberof HawksightPool
     */
    id?: string;

    /**
     * Name of the pool, typically indicating the token pair.
     *
     * @type {string}
     * @memberof HawksightPool
     */
    name?: string;

    /**
     * URL for the pool on the respective platform.
     *
     * @type {string}
     * @memberof HawksightPool
     */
    url?: string;

    /**
     * The protocol to which the pool belongs.
     *
     * @type {string}
     * @memberof HawksightPool
     */
    protocol?: string;

    /**
     * @type {MeteoraConfig | OrcaConfig}
     * @memberof HawksightPool
     */
    config?: MeteoraConfig | OrcaConfig;

    /**
     * @type {HawksightPoolMetrics}
     * @memberof HawksightPool
     */
    metrics?: HawksightPoolMetrics;
}
