/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse2004ComputeBudgetInstructions } from './inline-response2004-compute-budget-instructions';
import { InlineResponse2004MainInstructions } from './inline-response2004-main-instructions';
 /**
 * 
 *
 * @export
 * @interface InlineResponse2004
 */
export interface InlineResponse2004 {

    /**
     * Description of the operation performed.
     *
     * @type {string}
     * @memberof InlineResponse2004
     */
    description?: string;

    /**
     * Estimated fee for the transaction in SOL.
     *
     * @type {string}
     * @memberof InlineResponse2004
     */
    estimatedFeeInSOL?: string;

    /**
     * List of address lookup table addresses used in the transaction.
     *
     * @type {Array<string>}
     * @memberof InlineResponse2004
     */
    addressLookupTableAddresses?: Array<string>;

    /**
     * @type {Array<InlineResponse2004ComputeBudgetInstructions>}
     * @memberof InlineResponse2004
     */
    computeBudgetInstructions?: Array<InlineResponse2004ComputeBudgetInstructions>;

    /**
     * @type {Array<InlineResponse2004MainInstructions>}
     * @memberof InlineResponse2004
     */
    mainInstructions?: Array<InlineResponse2004MainInstructions>;
}
