/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse2001Data } from './inline-response2001-data';
 /**
 * 
 *
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {

    /**
     * @type {InlineResponse2001Data}
     * @memberof InlineResponse2001
     */
    data?: InlineResponse2001Data;

    /**
     * Indicates if the request was successful.
     *
     * @type {boolean}
     * @memberof InlineResponse2001
     */
    success?: boolean;

    /**
     * @type {any}
     * @memberof InlineResponse2001
     */
    example?: any;
}
