/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PoolsConfig } from './pools-config';
 /**
 * 
 *
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {

    /**
     * The unique identifier of the pool.
     *
     * @type {string}
     * @memberof InlineResponse2001
     * @example ARwi1S4DaiTG5DX7S4M4ZsrXqpMD1MrTmbu9ue2tpmEq
     */
    id?: string;

    /**
     * The name of the pool.
     *
     * @type {string}
     * @memberof InlineResponse2001
     * @example USDC-USDT
     */
    name?: string;

    /**
     * The URL of the pool.
     *
     * @type {string}
     * @memberof InlineResponse2001
     * @example https://app.meteora.ag/dlmm/ARwi1S4DaiTG5DX7S4M4ZsrXqpMD1MrTmbu9ue2tpmEq
     */
    url?: string;

    /**
     * Tags associated with the pool.
     *
     * @type {Array<string>}
     * @memberof InlineResponse2001
     * @example ["stable","stablecoins"]
     */
    tags?: Array<string>;

    /**
     * The protocol of the pool.
     *
     * @type {string}
     * @memberof InlineResponse2001
     * @example meteora
     */
    protocol?: string;

    /**
     * Whether pool is hidden or not.
     *
     * @type {boolean}
     * @memberof InlineResponse2001
     * @example false
     */
    hidden?: boolean;

    /**
     * @type {PoolsConfig}
     * @memberof InlineResponse2001
     */
    config?: PoolsConfig;
}
