/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse2004ComputeBudgetInstructions
 */
export interface InlineResponse2004ComputeBudgetInstructions {

    /**
     * List of accounts related to the compute budget instructions.
     *
     * @type {Array}
     * @memberof InlineResponse2004ComputeBudgetInstructions
     */
    accounts?: Array<any>;

    /**
     * Encoded data for the compute budget operation.
     *
     * @type {string}
     * @memberof InlineResponse2004ComputeBudgetInstructions
     */
    data?: string;

    /**
     * Program identifier for the compute budget.
     *
     * @type {string}
     * @memberof InlineResponse2004ComputeBudgetInstructions
     */
    programId?: string;
}
