/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OrcautilpoolsFeeApr } from './orcautilpools-fee-apr';
import { OrcautilpoolsPriceRange } from './orcautilpools-price-range';
import { OrcautilpoolsReward0Apr } from './orcautilpools-reward0-apr';
import { OrcautilpoolsReward1Apr } from './orcautilpools-reward1-apr';
import { OrcautilpoolsReward2Apr } from './orcautilpools-reward2-apr';
import { OrcautilpoolsTokenA } from './orcautilpools-token-a';
import { OrcautilpoolsTokenB } from './orcautilpools-token-b';
import { OrcautilpoolsTotalApr } from './orcautilpools-total-apr';
import { OrcautilpoolsVolume } from './orcautilpools-volume';
import { OrcautilpoolsVolumeDenominatedA } from './orcautilpools-volume-denominated-a';
import { OrcautilpoolsVolumeDenominatedB } from './orcautilpools-volume-denominated-b';
 /**
 * 
 *
 * @export
 * @interface InlineResponse2006
 */
export interface InlineResponse2006 {

    /**
     * The unique address identifier for the whirlpool.
     *
     * @type {string}
     * @memberof InlineResponse2006
     */
    address?: string;

    /**
     * @type {OrcautilpoolsTokenA}
     * @memberof InlineResponse2006
     */
    tokenA?: OrcautilpoolsTokenA;

    /**
     * @type {OrcautilpoolsTokenB}
     * @memberof InlineResponse2006
     */
    tokenB?: OrcautilpoolsTokenB;

    /**
     * Indicates if the whirlpool is whitelisted.
     *
     * @type {boolean}
     * @memberof InlineResponse2006
     */
    whitelisted?: boolean;

    /**
     * Tick spacing used in the pool.
     *
     * @type {number}
     * @memberof InlineResponse2006
     */
    tickSpacing?: number;

    /**
     * Current price of token A in terms of token B.
     *
     * @type {number}
     * @memberof InlineResponse2006
     */
    price?: number;

    /**
     * Liquidity provider fee rate for the pool.
     *
     * @type {number}
     * @memberof InlineResponse2006
     */
    lpFeeRate?: number;

    /**
     * Protocol fee rate for the pool.
     *
     * @type {number}
     * @memberof InlineResponse2006
     */
    protocolFeeRate?: number;

    /**
     * Identifier for the whirlpool configuration.
     *
     * @type {string}
     * @memberof InlineResponse2006
     */
    whirlpoolsConfig?: string;

    /**
     * Last modified time of the pool in milliseconds.
     *
     * @type {number}
     * @memberof InlineResponse2006
     */
    modifiedTimeMs?: number;

    /**
     * Total value locked in the pool.
     *
     * @type {number}
     * @memberof InlineResponse2006
     */
    tvl?: number;

    /**
     * @type {OrcautilpoolsVolume}
     * @memberof InlineResponse2006
     */
    volume?: OrcautilpoolsVolume;

    /**
     * @type {OrcautilpoolsVolumeDenominatedA}
     * @memberof InlineResponse2006
     */
    volumeDenominatedA?: OrcautilpoolsVolumeDenominatedA;

    /**
     * @type {OrcautilpoolsVolumeDenominatedB}
     * @memberof InlineResponse2006
     */
    volumeDenominatedB?: OrcautilpoolsVolumeDenominatedB;

    /**
     * @type {OrcautilpoolsPriceRange}
     * @memberof InlineResponse2006
     */
    priceRange?: OrcautilpoolsPriceRange;

    /**
     * @type {OrcautilpoolsFeeApr}
     * @memberof InlineResponse2006
     */
    feeApr?: OrcautilpoolsFeeApr;

    /**
     * @type {OrcautilpoolsReward0Apr}
     * @memberof InlineResponse2006
     */
    reward0Apr?: OrcautilpoolsReward0Apr;

    /**
     * @type {OrcautilpoolsReward1Apr}
     * @memberof InlineResponse2006
     */
    reward1Apr?: OrcautilpoolsReward1Apr;

    /**
     * @type {OrcautilpoolsReward2Apr}
     * @memberof InlineResponse2006
     */
    reward2Apr?: OrcautilpoolsReward2Apr;

    /**
     * @type {OrcautilpoolsTotalApr}
     * @memberof InlineResponse2006
     */
    totalApr?: OrcautilpoolsTotalApr;
}
