/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {

    /**
     * The wallet address of the user.
     *
     * @type {string}
     * @memberof InlineResponse200
     */
    wallet?: string;

    /**
     * The associated Program Derived Address (PDA) of the user.
     *
     * @type {string}
     * @memberof InlineResponse200
     */
    userPda?: string;

    /**
     * @type {{ [key: string]: Array<any>; }}
     * @memberof InlineResponse200
     */
    pools?: { [key: string]: Array<any>; };
}
