/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse400
 */
export interface InlineResponse400 {

    /**
     * Error code identifying the type of error.
     *
     * @type {string}
     * @memberof InlineResponse400
     */
    code?: string;

    /**
     * A descriptive message explaining the error.
     *
     * @type {string}
     * @memberof InlineResponse400
     */
    message?: string;

    /**
     * The path in the request body that led to the error.
     *
     * @type {Array<string>}
     * @memberof InlineResponse400
     */
    path?: Array<string>;
}
