/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse2002Data } from './inline-response2002-data';
 /**
 * 
 *
 * @export
 * @interface InlineResponse2002
 */
export interface InlineResponse2002 {

    /**
     * @type {InlineResponse2002Data}
     * @memberof InlineResponse2002
     */
    data?: InlineResponse2002Data;

    /**
     * Indicates if the request was successful.
     *
     * @type {boolean}
     * @memberof InlineResponse2002
     */
    success?: boolean;

    /**
     * @type {any}
     * @memberof InlineResponse2002
     */
    example?: any;
}
