/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse2002DataItems } from './inline-response2002-data-items';
 /**
 * 
 *
 * @export
 * @interface InlineResponse2002Data
 */
export interface InlineResponse2002Data {

    /**
     * @type {Array<InlineResponse2002DataItems>}
     * @memberof InlineResponse2002Data
     */
    items?: Array<InlineResponse2002DataItems>;
}
