/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse2004Accounts } from './inline-response2004-accounts';
 /**
 * 
 *
 * @export
 * @interface InlineResponse2004MainInstructions
 */
export interface InlineResponse2004MainInstructions {

    /**
     * @type {Array<InlineResponse2004Accounts>}
     * @memberof InlineResponse2004MainInstructions
     */
    accounts?: Array<InlineResponse2004Accounts>;

    /**
     * Encoded data related to the main transaction instructions.
     *
     * @type {string}
     * @memberof InlineResponse2004MainInstructions
     */
    data?: string;

    /**
     * Program identifier for the main transaction.
     *
     * @type {string}
     * @memberof InlineResponse2004MainInstructions
     */
    programId?: string;
}
