/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse2005
 */
export interface InlineResponse2005 {

    /**
     * The unique address identifier for the pool.
     *
     * @type {string}
     * @memberof InlineResponse2005
     */
    address?: string;

    /**
     * Name of the pool, typically indicating the token pair.
     *
     * @type {string}
     * @memberof InlineResponse2005
     */
    name?: string;

    /**
     * Token mint address for the X asset in the pool.
     *
     * @type {string}
     * @memberof InlineResponse2005
     */
    mintX?: string;

    /**
     * Token mint address for the Y asset in the pool.
     *
     * @type {string}
     * @memberof InlineResponse2005
     */
    mintY?: string;

    /**
     * Reserve account address for the X asset.
     *
     * @type {string}
     * @memberof InlineResponse2005
     */
    reserveX?: string;

    /**
     * Reserve account address for the Y asset.
     *
     * @type {string}
     * @memberof InlineResponse2005
     */
    reserveY?: string;

    /**
     * Amount of X asset in the reserve.
     *
     * @type {number}
     * @memberof InlineResponse2005
     */
    reserveXAmount?: number;

    /**
     * Amount of Y asset in the reserve.
     *
     * @type {number}
     * @memberof InlineResponse2005
     */
    reserveYAmount?: number;

    /**
     * The bin step size used in the pool's operation.
     *
     * @type {number}
     * @memberof InlineResponse2005
     */
    binStep?: number;

    /**
     * Base fee percentage charged for transactions in the pool.
     *
     * @type {string}
     * @memberof InlineResponse2005
     */
    baseFeePercentage?: string;

    /**
     * Maximum possible fee percentage that can be charged.
     *
     * @type {string}
     * @memberof InlineResponse2005
     */
    maxFeePercentage?: string;

    /**
     * Fee percentage taken by the protocol.
     *
     * @type {string}
     * @memberof InlineResponse2005
     */
    protocolFeePercentage?: string;

    /**
     * Current liquidity in the pool.
     *
     * @type {string}
     * @memberof InlineResponse2005
     */
    liquidity?: string;

    /**
     * Reward mint address for the X asset.
     *
     * @type {string}
     * @memberof InlineResponse2005
     */
    rewardMintX?: string;

    /**
     * Reward mint address for the Y asset.
     *
     * @type {string}
     * @memberof InlineResponse2005
     */
    rewardMintY?: string;

    /**
     * Fees generated in the pool over the last 24 hours.
     *
     * @type {number}
     * @memberof InlineResponse2005
     */
    fees24h?: number;

    /**
     * Fees generated in the pool today.
     *
     * @type {number}
     * @memberof InlineResponse2005
     */
    todayFees?: number;

    /**
     * Trade volume in the pool over the last 24 hours.
     *
     * @type {number}
     * @memberof InlineResponse2005
     */
    tradeVolume24h?: number;

    /**
     * Cumulative trade volume in the pool since inception.
     *
     * @type {string}
     * @memberof InlineResponse2005
     */
    cumulativeTradeVolume?: string;

    /**
     * Cumulative fees generated by the pool since inception.
     *
     * @type {string}
     * @memberof InlineResponse2005
     */
    cumulativeFeeVolume?: string;

    /**
     * Current price of X asset in terms of Y asset.
     *
     * @type {number}
     * @memberof InlineResponse2005
     */
    currentPrice?: number;

    /**
     * Annual Percentage Rate for earnings in the pool.
     *
     * @type {number}
     * @memberof InlineResponse2005
     */
    apr?: number;

    /**
     * Annual Percentage Yield for earnings in the pool.
     *
     * @type {number}
     * @memberof InlineResponse2005
     */
    apy?: number;

    /**
     * APR for farming activities associated with the pool.
     *
     * @type {number}
     * @memberof InlineResponse2005
     */
    farmApr?: number;

    /**
     * APY for farming activities associated with the pool.
     *
     * @type {number}
     * @memberof InlineResponse2005
     */
    farmApy?: number;

    /**
     * Indicates whether the pool is hidden from default views.
     *
     * @type {boolean}
     * @memberof InlineResponse2005
     */
    hide?: boolean;
}
