/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse2001DataItems } from './inline-response2001-data-items';
 /**
 * 
 *
 * @export
 * @interface InlineResponse2001Data
 */
export interface InlineResponse2001Data {

    /**
     * @type {Array<InlineResponse2001DataItems>}
     * @memberof InlineResponse2001Data
     */
    items?: Array<InlineResponse2001DataItems>;
}
