/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OrcautilpoolPriceRange } from './orcautilpool-price-range';
import { OrcautilpoolTokenA } from './orcautilpool-token-a';
import { OrcautilpoolVolume } from './orcautilpool-volume';
 /**
 * 
 *
 * @export
 * @interface InlineResponse2006
 */
export interface InlineResponse2006 {

    /**
     * Address of the Orca pool
     *
     * @type {string}
     * @memberof InlineResponse2006
     */
    address?: string;

    /**
     * @type {OrcautilpoolTokenA}
     * @memberof InlineResponse2006
     */
    tokenA?: OrcautilpoolTokenA;

    /**
     * @type {OrcautilpoolTokenA}
     * @memberof InlineResponse2006
     */
    tokenB?: OrcautilpoolTokenA;

    /**
     * @type {boolean}
     * @memberof InlineResponse2006
     */
    whitelisted?: boolean;

    /**
     * @type {boolean}
     * @memberof InlineResponse2006
     */
    token2022?: boolean;

    /**
     * @type {number}
     * @memberof InlineResponse2006
     */
    tickSpacing?: number;

    /**
     * @type {number}
     * @memberof InlineResponse2006
     */
    price?: number;

    /**
     * @type {number}
     * @memberof InlineResponse2006
     */
    lpFeeRate?: number;

    /**
     * @type {number}
     * @memberof InlineResponse2006
     */
    protocolFeeRate?: number;

    /**
     * @type {string}
     * @memberof InlineResponse2006
     */
    whirlpoolsConfig?: string;

    /**
     * @type {number}
     * @memberof InlineResponse2006
     */
    modifiedTimeMs?: number;

    /**
     * @type {number}
     * @memberof InlineResponse2006
     */
    tvl?: number;

    /**
     * @type {OrcautilpoolVolume}
     * @memberof InlineResponse2006
     */
    volume?: OrcautilpoolVolume;

    /**
     * @type {OrcautilpoolVolume}
     * @memberof InlineResponse2006
     */
    volumeDenominatedA?: OrcautilpoolVolume;

    /**
     * @type {OrcautilpoolVolume}
     * @memberof InlineResponse2006
     */
    volumeDenominatedB?: OrcautilpoolVolume;

    /**
     * @type {OrcautilpoolPriceRange}
     * @memberof InlineResponse2006
     */
    priceRange?: OrcautilpoolPriceRange;

    /**
     * @type {OrcautilpoolVolume}
     * @memberof InlineResponse2006
     */
    feeApr?: OrcautilpoolVolume;

    /**
     * @type {OrcautilpoolVolume}
     * @memberof InlineResponse2006
     */
    reward0Apr?: OrcautilpoolVolume;

    /**
     * @type {OrcautilpoolVolume}
     * @memberof InlineResponse2006
     */
    reward1Apr?: OrcautilpoolVolume;

    /**
     * @type {OrcautilpoolVolume}
     * @memberof InlineResponse2006
     */
    reward2Apr?: OrcautilpoolVolume;

    /**
     * @type {OrcautilpoolVolume}
     * @memberof InlineResponse2006
     */
    totalApr?: OrcautilpoolVolume;
}
