/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Account } from './account';
 /**
 * 
 *
 * @export
 * @interface Instruction
 */
export interface Instruction {

    /**
     * @type {Array<Account>}
     * @memberof Instruction
     */
    accounts?: Array<Account>;

    /**
     * Base-64 encoded data for the instruction.
     *
     * @type {string}
     * @memberof Instruction
     */
    data?: string;

    /**
     * Solana program to execute.
     *
     * @type {string}
     * @memberof Instruction
     */
    programId?: string;
}
