/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface MeteoraPositionInner
 */
export interface MeteoraPositionInner {

    /**
     * The identifier of the Meteora position.
     *
     * @type {string}
     * @memberof MeteoraPositionInner
     */
    position?: string;

    /**
     * The user's wallet address.
     *
     * @type {string}
     * @memberof MeteoraPositionInner
     */
    userWallet?: string;

    /**
     * The user's PDA (Program Derived Address).
     *
     * @type {string}
     * @memberof MeteoraPositionInner
     */
    userPda?: string;

    /**
     * The identifier of the pool.
     *
     * @type {string}
     * @memberof MeteoraPositionInner
     */
    pool?: string;

    /**
     * The transaction ID of the position creation.
     *
     * @type {string}
     * @memberof MeteoraPositionInner
     */
    creationTx?: string;
}
