/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Additional fast generation options
 *
 * @export
 * @interface MeteoradlmmtxwithdrawFastGeneration
 */
export interface MeteoradlmmtxwithdrawFastGeneration {

    /**
     * Pool address
     *
     * @type {string}
     * @memberof MeteoradlmmtxwithdrawFastGeneration
     */
    pool?: string;

    /**
     * Array of bin IDs to remove
     *
     * @type {Array<number>}
     * @memberof MeteoradlmmtxwithdrawFastGeneration
     */
    binIdsToRemove?: Array<number>;
}
