/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Optional fast generation settings
 *
 * @export
 * @interface MeteoradlmmtxdepositFastGeneration
 */
export interface MeteoradlmmtxdepositFastGeneration {

    /**
     * Address of the pool
     *
     * @type {string}
     * @memberof MeteoradlmmtxdepositFastGeneration
     */
    pool: string;

    /**
     * Upper bin ID for the pool
     *
     * @type {number}
     * @memberof MeteoradlmmtxdepositFastGeneration
     */
    upperBinId: number;

    /**
     * Lower bin ID for the pool
     *
     * @type {number}
     * @memberof MeteoradlmmtxdepositFastGeneration
     */
    lowerBinId: number;
}
