/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface MeteoradlmmutilpoolsMetricsRewardsBase
 */
export interface MeteoradlmmutilpoolsMetricsRewardsBase {

    /**
     * Mint address of the reward token.
     *
     * @type {string}
     * @memberof MeteoradlmmutilpoolsMetricsRewardsBase
     */
    mint?: string;

    /**
     * Amount of the reward token.
     *
     * @type {number}
     * @memberof MeteoradlmmutilpoolsMetricsRewardsBase
     */
    amount?: number;
}
