/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PoolBaseConfig } from './pool-base-config';
 /**
 * 
 *
 * @export
 * @interface MeteoraConfig
 */
export interface MeteoraConfig extends PoolBaseConfig {

    /**
     * Reward mint address for the A asset.
     *
     * @type {string}
     * @memberof MeteoraConfig
     */
    rewardMintA?: string;

    /**
     * Reward mint address for the B asset.
     *
     * @type {string}
     * @memberof MeteoraConfig
     */
    rewardMintB?: string;

    /**
     * The bin step size used in the pool's operation.
     *
     * @type {number}
     * @memberof MeteoraConfig
     */
    binStep?: number;
}
