/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface OrcautilpoolTokenA
 */
export interface OrcautilpoolTokenA {

    /**
     * @type {string}
     * @memberof OrcautilpoolTokenA
     */
    mint?: string;

    /**
     * @type {string}
     * @memberof OrcautilpoolTokenA
     */
    symbol?: string;

    /**
     * @type {string}
     * @memberof OrcautilpoolTokenA
     */
    name?: string;

    /**
     * @type {number}
     * @memberof OrcautilpoolTokenA
     */
    decimals?: number;

    /**
     * @type {string}
     * @memberof OrcautilpoolTokenA
     */
    logoURI?: string;

    /**
     * @type {string}
     * @memberof OrcautilpoolTokenA
     */
    coingeckoId?: string;

    /**
     * @type {boolean}
     * @memberof OrcautilpoolTokenA
     */
    whitelisted?: boolean;

    /**
     * @type {boolean}
     * @memberof OrcautilpoolTokenA
     */
    poolToken?: boolean;

    /**
     * @type {boolean}
     * @memberof OrcautilpoolTokenA
     */
    token2022?: boolean;
}
