/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OrcaConfigRewards } from './orca-config-rewards';
import { PoolBaseConfig } from './pool-base-config';
 /**
 * 
 *
 * @export
 * @interface OrcaConfig
 */
export interface OrcaConfig extends PoolBaseConfig {

    /**
     * Configuration address for the Whirlpool.
     *
     * @type {string}
     * @memberof OrcaConfig
     */
    whirlpoolConfig?: string;

    /**
     * @type {Array<OrcaConfigRewards>}
     * @memberof OrcaConfig
     */
    rewards?: Array<OrcaConfigRewards>;

    /**
     * Tick spacing for the pool.
     *
     * @type {number}
     * @memberof OrcaConfig
     */
    tickSpacing?: number;

    /**
     * Fee rate for the pool.
     *
     * @type {number}
     * @memberof OrcaConfig
     */
    feeRate?: number;
}
