/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Trading volume denominated in token A.
 *
 * @export
 * @interface OrcautilpoolsVolumeDenominatedA
 */
export interface OrcautilpoolsVolumeDenominatedA {

    /**
     * Daily volume in token A.
     *
     * @type {number}
     * @memberof OrcautilpoolsVolumeDenominatedA
     */
    day?: number;

    /**
     * Weekly volume in token A.
     *
     * @type {number}
     * @memberof OrcautilpoolsVolumeDenominatedA
     */
    week?: number;

    /**
     * Monthly volume in token A.
     *
     * @type {number}
     * @memberof OrcautilpoolsVolumeDenominatedA
     */
    month?: number;
}
