/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Trading volume denominated in token B.
 *
 * @export
 * @interface OrcautilpoolsVolumeDenominatedB
 */
export interface OrcautilpoolsVolumeDenominatedB {

    /**
     * Daily volume in token B.
     *
     * @type {number}
     * @memberof OrcautilpoolsVolumeDenominatedB
     */
    day?: number;

    /**
     * Weekly volume in token B.
     *
     * @type {number}
     * @memberof OrcautilpoolsVolumeDenominatedB
     */
    week?: number;

    /**
     * Monthly volume in token B.
     *
     * @type {number}
     * @memberof OrcautilpoolsVolumeDenominatedB
     */
    month?: number;
}
