/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Weekly price range.
 *
 * @export
 * @interface OrcautilpoolsPriceRangeWeek
 */
export interface OrcautilpoolsPriceRangeWeek {

    /**
     * Minimum price of the week.
     *
     * @type {number}
     * @memberof OrcautilpoolsPriceRangeWeek
     */
    min?: number;

    /**
     * Maximum price of the week.
     *
     * @type {number}
     * @memberof OrcautilpoolsPriceRangeWeek
     */
    max?: number;
}
