/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Trading volume statistics for the pool.
 *
 * @export
 * @interface OrcautilpoolsVolume
 */
export interface OrcautilpoolsVolume {

    /**
     * Daily trading volume.
     *
     * @type {number}
     * @memberof OrcautilpoolsVolume
     */
    day?: number;

    /**
     * Weekly trading volume.
     *
     * @type {number}
     * @memberof OrcautilpoolsVolume
     */
    week?: number;

    /**
     * Monthly trading volume.
     *
     * @type {number}
     * @memberof OrcautilpoolsVolume
     */
    month?: number;
}
