/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface OrcaConfigRewards
 */
export interface OrcaConfigRewards {

    /**
     * Vault address for the reward.
     *
     * @type {string}
     * @memberof OrcaConfigRewards
     */
    vault?: string;

    /**
     * Mint address of the reward token.
     *
     * @type {string}
     * @memberof OrcaConfigRewards
     */
    mint?: string;
}
