/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OrcautilpoolPriceRangeDay } from './orcautilpool-price-range-day';
 /**
 * 
 *
 * @export
 * @interface OrcautilpoolPriceRange
 */
export interface OrcautilpoolPriceRange {

    /**
     * @type {OrcautilpoolPriceRangeDay}
     * @memberof OrcautilpoolPriceRange
     */
    day?: OrcautilpoolPriceRangeDay;

    /**
     * @type {OrcautilpoolPriceRangeDay}
     * @memberof OrcautilpoolPriceRange
     */
    week?: OrcautilpoolPriceRangeDay;

    /**
     * @type {OrcautilpoolPriceRangeDay}
     * @memberof OrcautilpoolPriceRange
     */
    month?: OrcautilpoolPriceRangeDay;
}
