/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OrcautilpoolsPriceRangeDay } from './orcautilpools-price-range-day';
import { OrcautilpoolsPriceRangeMonth } from './orcautilpools-price-range-month';
import { OrcautilpoolsPriceRangeWeek } from './orcautilpools-price-range-week';
 /**
 * Price range statistics for the pool.
 *
 * @export
 * @interface OrcautilpoolsPriceRange
 */
export interface OrcautilpoolsPriceRange {

    /**
     * @type {OrcautilpoolsPriceRangeDay}
     * @memberof OrcautilpoolsPriceRange
     */
    day?: OrcautilpoolsPriceRangeDay;

    /**
     * @type {OrcautilpoolsPriceRangeWeek}
     * @memberof OrcautilpoolsPriceRange
     */
    week?: OrcautilpoolsPriceRangeWeek;

    /**
     * @type {OrcautilpoolsPriceRangeMonth}
     * @memberof OrcautilpoolsPriceRange
     */
    month?: OrcautilpoolsPriceRangeMonth;
}
