/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { UserPositionInfo } from './user-position-info';
 /**
 * 
 *
 * @export
 * @interface PoolOut
 */
export interface PoolOut extends UserPositionInfo {

    /**
     * The address of the position within the pool.
     *
     * @type {string}
     * @memberof PoolOut
     */
    positionAddress?: string;
}
