/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * The fee estimates for different priority levels
 *
 * @export
 * @interface PriorityFeeEstimateFeeLevels
 */
export interface PriorityFeeEstimateFeeLevels {

    /**
     * The fee estimate for the low priority level
     *
     * @type {number}
     * @memberof PriorityFeeEstimateFeeLevels
     */
    low?: number;

    /**
     * The fee estimate for the default priority level
     *
     * @type {number}
     * @memberof PriorityFeeEstimateFeeLevels
     */
    _default?: number;

    /**
     * The fee estimate for the high priority level
     *
     * @type {number}
     * @memberof PriorityFeeEstimateFeeLevels
     */
    high?: number;

    /**
     * The fee estimate for the very high priority level
     *
     * @type {number}
     * @memberof PriorityFeeEstimateFeeLevels
     */
    veryHigh?: number;
}
