/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Instruction } from './instruction';
 /**
 * 
 *
 * @export
 * @interface TransactionMetadata
 */
export interface TransactionMetadata {

    /**
     * Description of the operation performed.
     *
     * @type {string}
     * @memberof TransactionMetadata
     */
    description?: string;

    /**
     * Estimated fee for the transaction in SOL.
     *
     * @type {string}
     * @memberof TransactionMetadata
     */
    estimatedFeeInSOL?: string;

    /**
     * List of address lookup table addresses used in the transaction.
     *
     * @type {Array<string>}
     * @memberof TransactionMetadata
     */
    addressLookupTableAddresses?: Array<string>;

    /**
     * @type {Array<Instruction>}
     * @memberof TransactionMetadata
     */
    computeBudgetInstructions?: Array<Instruction>;

    /**
     * @type {Array<Instruction>}
     * @memberof TransactionMetadata
     */
    mainInstructions?: Array<Instruction>;

    /**
     * Transaction payer (encoded in base58 string)
     *
     * @type {string}
     * @memberof TransactionMetadata
     */
    payer?: string;

    /**
     * Secured signature used to verify the origin and integrity of the response. This signature is typically generated using a cryptographic hash function combined with a secret key to ensure that the response is not altered and comes from a trusted source. The signature helps in validating that the response was indeed sent by the expected party and has not been tampered with during transit. 
     *
     * @type {string}
     * @memberof TransactionMetadata
     */
    signature?: string;
}
