/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TxClosePositionBody
 */
export interface TxClosePositionBody {

    /**
     * Transaction priority (Default, Low, Medium, High, VeryHigh, UnsafeMax, None)
     *
     * @type {string}
     * @memberof TxClosePositionBody
     */
    priority?: string;

    /**
     * Max lamports to consume for priority fee
     *
     * @type {number}
     * @memberof TxClosePositionBody
     */
    maxPriorityFee?: number;

    /**
     * User's wallet address who owns the position.
     *
     * @type {string}
     * @memberof TxClosePositionBody
     */
    userWallet?: string;

    /**
     * User's position from Meteora (See GET /meteora/dlmm/util/positions).
     *
     * @type {string}
     * @memberof TxClosePositionBody
     */
    position?: string;
}
