/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MeteoradlmmtxdepositFastGeneration } from './meteoradlmmtxdeposit-fast-generation';
 /**
 * 
 *
 * @export
 * @interface TxDepositBody
 */
export interface TxDepositBody {

    /**
     * User's position from meteora (See GET /meteora/dlmm/util/positions)
     *
     * @type {string}
     * @memberof TxDepositBody
     */
    position?: string;

    /**
     * User's wallet address who owns the position
     *
     * @type {string}
     * @memberof TxDepositBody
     */
    userWallet?: string;

    /**
     * Amount of X tokens to deposit
     *
     * @type {number}
     * @memberof TxDepositBody
     */
    totalXAmount?: number;

    /**
     * Amount of Y tokens to deposit
     *
     * @type {number}
     * @memberof TxDepositBody
     */
    totalYAmount?: number;

    /**
     * X and Y token distribution. At the moment, we support default meteora distribution functions: SPOT, CURVE, BID-ASK, SPOT-IMBALANCED, CURVE-IMBALANCED, BID-ASK-IMBALANCED
     *
     * @type {string}
     * @memberof TxDepositBody
     */
    distribution?: string;

    /**
     * Liquidity slippage (default: 3. 3 means 0.03%)
     *
     * @type {number}
     * @memberof TxDepositBody
     */
    slippage?: number;

    /**
     * Whether to skip input token check (improves tx generation)
     *
     * @type {boolean}
     * @memberof TxDepositBody
     */
    skipInputTokenCheck?: boolean;

    /**
     * @type {MeteoradlmmtxdepositFastGeneration}
     * @memberof TxDepositBody
     */
    fastGeneration?: MeteoradlmmtxdepositFastGeneration;
}
