/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { UserPools } from './user-pools';
 /**
 * 
 *
 * @export
 * @interface UserPortfolio
 */
export interface UserPortfolio {

    /**
     * The wallet address of the user.
     *
     * @type {string}
     * @memberof UserPortfolio
     */
    wallet?: string;

    /**
     * The associated Program Derived Address (PDA) of the user.
     *
     * @type {string}
     * @memberof UserPortfolio
     */
    userPda?: string;

    /**
     * @type {{ [key: string]: UserPools; }}
     * @memberof UserPortfolio
     */
    pools?: { [key: string]: UserPools; };
}
