/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PoolOut } from './pool-out';
 /**
 * 
 *
 * @export
 * @interface UserPools
 */
export interface UserPools {

    /**
     * @type {PoolOut}
     * @memberof UserPools
     */
    items?: PoolOut;
}
