/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PriorityLevel } from './priority-level';
import { TransactionMetadata } from './transaction-metadata';
 /**
 * 
 *
 * @export
 * @interface UtilGetPriorityFeeEstimateBody
 */
export interface UtilGetPriorityFeeEstimateBody {

    /**
     * @type {PriorityLevel}
     * @memberof UtilGetPriorityFeeEstimateBody
     */
    priority?: PriorityLevel;

    /**
     * @type {TransactionMetadata}
     * @memberof UtilGetPriorityFeeEstimateBody
     */
    transaction?: TransactionMetadata;
}
