/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AutomationCompoundAutomationIxBody } from '../models';
import { InlineResponse400 } from '../models';
import { TransactionMetadata } from '../models';
/**
 * MeteoraDLMMAutomationInstructionsApi - axios parameter creator
 * @export
 */
export const MeteoraDLMMAutomationInstructionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Generates a compound transaction instruction for Meteora DLMM, to be signed by Hawksight authority. This allows users to modify their positions based on specified parameters.
         * @param {AutomationCompoundAutomationIxBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meteoraDlmmAutomationCompoundAutomationIxPost: async (body: AutomationCompoundAutomationIxBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling meteoraDlmmAutomationCompoundAutomationIxPost.');
            }
            const localVarPath = `/meteora/dlmm/automation/compoundAutomationIx`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MeteoraDLMMAutomationInstructionsApi - functional programming interface
 * @export
 */
export const MeteoraDLMMAutomationInstructionsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Generates a compound transaction instruction for Meteora DLMM, to be signed by Hawksight authority. This allows users to modify their positions based on specified parameters.
         * @param {AutomationCompoundAutomationIxBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meteoraDlmmAutomationCompoundAutomationIxPost(body: AutomationCompoundAutomationIxBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<TransactionMetadata>>> {
            const localVarAxiosArgs = await MeteoraDLMMAutomationInstructionsApiAxiosParamCreator(configuration).meteoraDlmmAutomationCompoundAutomationIxPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MeteoraDLMMAutomationInstructionsApi - factory interface
 * @export
 */
export const MeteoraDLMMAutomationInstructionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Generates a compound transaction instruction for Meteora DLMM, to be signed by Hawksight authority. This allows users to modify their positions based on specified parameters.
         * @param {AutomationCompoundAutomationIxBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meteoraDlmmAutomationCompoundAutomationIxPost(body: AutomationCompoundAutomationIxBody, options?: AxiosRequestConfig): Promise<AxiosResponse<TransactionMetadata>> {
            return MeteoraDLMMAutomationInstructionsApiFp(configuration).meteoraDlmmAutomationCompoundAutomationIxPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MeteoraDLMMAutomationInstructionsApi - object-oriented interface
 * @export
 * @class MeteoraDLMMAutomationInstructionsApi
 * @extends {BaseAPI}
 */
export class MeteoraDLMMAutomationInstructionsApi extends BaseAPI {
    /**
     * Generates a compound transaction instruction for Meteora DLMM, to be signed by Hawksight authority. This allows users to modify their positions based on specified parameters.
     * @param {AutomationCompoundAutomationIxBody} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MeteoraDLMMAutomationInstructionsApi
     */
    public async meteoraDlmmAutomationCompoundAutomationIxPost(body: AutomationCompoundAutomationIxBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<TransactionMetadata>> {
        return MeteoraDLMMAutomationInstructionsApiFp(this.configuration).meteoraDlmmAutomationCompoundAutomationIxPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
