/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { InlineResponse400 } from '../models';
import { TransactionMetadata } from '../models';
import { TxClaimBody } from '../models';
import { TxClosePositionBody } from '../models';
import { TxCreatePositionAndDepositBody } from '../models';
import { TxDepositBody } from '../models';
import { TxInitializeBinArraysBody } from '../models';
import { TxWithdrawBody } from '../models';
/**
 * MeteoraDLMMInstructionsApi - axios parameter creator
 * @export
 */
export const MeteoraDLMMInstructionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Return Solana instructions that create a position and deposit to Meteora via Hawksight.
         * @param {TxClaimBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meteoraDlmmTxClaimPost: async (body: TxClaimBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling meteoraDlmmTxClaimPost.');
            }
            const localVarPath = `/meteora/dlmm/tx/claim`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Return Solana instructions that create a position and deposit to Meteora via Hawksight.
         * @param {TxClosePositionBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meteoraDlmmTxClosePositionPost: async (body: TxClosePositionBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling meteoraDlmmTxClosePositionPost.');
            }
            const localVarPath = `/meteora/dlmm/tx/closePosition`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Return solana instructions that creates position and deposit to meteora via hawksight.
         * @param {TxCreatePositionAndDepositBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meteoraDlmmTxCreatePositionAndDepositPost: async (body: TxCreatePositionAndDepositBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling meteoraDlmmTxCreatePositionAndDepositPost.');
            }
            const localVarPath = `/meteora/dlmm/tx/createPositionAndDeposit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Return solana instructions that deposits to target position in meteora via hawksight.
         * @param {TxDepositBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meteoraDlmmTxDepositPost: async (body: TxDepositBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling meteoraDlmmTxDepositPost.');
            }
            const localVarPath = `/meteora/dlmm/tx/deposit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Return Solana instructions that create a position and deposit to Meteora via Hawksight.
         * @param {TxInitializeBinArraysBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meteoraDlmmTxInitializeBinArraysPost: async (body: TxInitializeBinArraysBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling meteoraDlmmTxInitializeBinArraysPost.');
            }
            const localVarPath = `/meteora/dlmm/tx/initializeBinArrays`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Return Solana instructions that create a position and deposit to Meteora via Hawksight.
         * @param {TxWithdrawBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meteoraDlmmTxWithdrawPost: async (body: TxWithdrawBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling meteoraDlmmTxWithdrawPost.');
            }
            const localVarPath = `/meteora/dlmm/tx/withdraw`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MeteoraDLMMInstructionsApi - functional programming interface
 * @export
 */
export const MeteoraDLMMInstructionsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Return Solana instructions that create a position and deposit to Meteora via Hawksight.
         * @param {TxClaimBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meteoraDlmmTxClaimPost(body: TxClaimBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<TransactionMetadata>>> {
            const localVarAxiosArgs = await MeteoraDLMMInstructionsApiAxiosParamCreator(configuration).meteoraDlmmTxClaimPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Return Solana instructions that create a position and deposit to Meteora via Hawksight.
         * @param {TxClosePositionBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meteoraDlmmTxClosePositionPost(body: TxClosePositionBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<TransactionMetadata>>> {
            const localVarAxiosArgs = await MeteoraDLMMInstructionsApiAxiosParamCreator(configuration).meteoraDlmmTxClosePositionPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Return solana instructions that creates position and deposit to meteora via hawksight.
         * @param {TxCreatePositionAndDepositBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meteoraDlmmTxCreatePositionAndDepositPost(body: TxCreatePositionAndDepositBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<TransactionMetadata>>> {
            const localVarAxiosArgs = await MeteoraDLMMInstructionsApiAxiosParamCreator(configuration).meteoraDlmmTxCreatePositionAndDepositPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Return solana instructions that deposits to target position in meteora via hawksight.
         * @param {TxDepositBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meteoraDlmmTxDepositPost(body: TxDepositBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<TransactionMetadata>>> {
            const localVarAxiosArgs = await MeteoraDLMMInstructionsApiAxiosParamCreator(configuration).meteoraDlmmTxDepositPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Return Solana instructions that create a position and deposit to Meteora via Hawksight.
         * @param {TxInitializeBinArraysBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meteoraDlmmTxInitializeBinArraysPost(body: TxInitializeBinArraysBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<TransactionMetadata>>> {
            const localVarAxiosArgs = await MeteoraDLMMInstructionsApiAxiosParamCreator(configuration).meteoraDlmmTxInitializeBinArraysPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Return Solana instructions that create a position and deposit to Meteora via Hawksight.
         * @param {TxWithdrawBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meteoraDlmmTxWithdrawPost(body: TxWithdrawBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<TransactionMetadata>>> {
            const localVarAxiosArgs = await MeteoraDLMMInstructionsApiAxiosParamCreator(configuration).meteoraDlmmTxWithdrawPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MeteoraDLMMInstructionsApi - factory interface
 * @export
 */
export const MeteoraDLMMInstructionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Return Solana instructions that create a position and deposit to Meteora via Hawksight.
         * @param {TxClaimBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meteoraDlmmTxClaimPost(body: TxClaimBody, options?: AxiosRequestConfig): Promise<AxiosResponse<TransactionMetadata>> {
            return MeteoraDLMMInstructionsApiFp(configuration).meteoraDlmmTxClaimPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Return Solana instructions that create a position and deposit to Meteora via Hawksight.
         * @param {TxClosePositionBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meteoraDlmmTxClosePositionPost(body: TxClosePositionBody, options?: AxiosRequestConfig): Promise<AxiosResponse<TransactionMetadata>> {
            return MeteoraDLMMInstructionsApiFp(configuration).meteoraDlmmTxClosePositionPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Return solana instructions that creates position and deposit to meteora via hawksight.
         * @param {TxCreatePositionAndDepositBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meteoraDlmmTxCreatePositionAndDepositPost(body: TxCreatePositionAndDepositBody, options?: AxiosRequestConfig): Promise<AxiosResponse<TransactionMetadata>> {
            return MeteoraDLMMInstructionsApiFp(configuration).meteoraDlmmTxCreatePositionAndDepositPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Return solana instructions that deposits to target position in meteora via hawksight.
         * @param {TxDepositBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meteoraDlmmTxDepositPost(body: TxDepositBody, options?: AxiosRequestConfig): Promise<AxiosResponse<TransactionMetadata>> {
            return MeteoraDLMMInstructionsApiFp(configuration).meteoraDlmmTxDepositPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Return Solana instructions that create a position and deposit to Meteora via Hawksight.
         * @param {TxInitializeBinArraysBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meteoraDlmmTxInitializeBinArraysPost(body: TxInitializeBinArraysBody, options?: AxiosRequestConfig): Promise<AxiosResponse<TransactionMetadata>> {
            return MeteoraDLMMInstructionsApiFp(configuration).meteoraDlmmTxInitializeBinArraysPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Return Solana instructions that create a position and deposit to Meteora via Hawksight.
         * @param {TxWithdrawBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meteoraDlmmTxWithdrawPost(body: TxWithdrawBody, options?: AxiosRequestConfig): Promise<AxiosResponse<TransactionMetadata>> {
            return MeteoraDLMMInstructionsApiFp(configuration).meteoraDlmmTxWithdrawPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MeteoraDLMMInstructionsApi - object-oriented interface
 * @export
 * @class MeteoraDLMMInstructionsApi
 * @extends {BaseAPI}
 */
export class MeteoraDLMMInstructionsApi extends BaseAPI {
    /**
     * Return Solana instructions that create a position and deposit to Meteora via Hawksight.
     * @param {TxClaimBody} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MeteoraDLMMInstructionsApi
     */
    public async meteoraDlmmTxClaimPost(body: TxClaimBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<TransactionMetadata>> {
        return MeteoraDLMMInstructionsApiFp(this.configuration).meteoraDlmmTxClaimPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Return Solana instructions that create a position and deposit to Meteora via Hawksight.
     * @param {TxClosePositionBody} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MeteoraDLMMInstructionsApi
     */
    public async meteoraDlmmTxClosePositionPost(body: TxClosePositionBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<TransactionMetadata>> {
        return MeteoraDLMMInstructionsApiFp(this.configuration).meteoraDlmmTxClosePositionPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Return solana instructions that creates position and deposit to meteora via hawksight.
     * @param {TxCreatePositionAndDepositBody} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MeteoraDLMMInstructionsApi
     */
    public async meteoraDlmmTxCreatePositionAndDepositPost(body: TxCreatePositionAndDepositBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<TransactionMetadata>> {
        return MeteoraDLMMInstructionsApiFp(this.configuration).meteoraDlmmTxCreatePositionAndDepositPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Return solana instructions that deposits to target position in meteora via hawksight.
     * @param {TxDepositBody} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MeteoraDLMMInstructionsApi
     */
    public async meteoraDlmmTxDepositPost(body: TxDepositBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<TransactionMetadata>> {
        return MeteoraDLMMInstructionsApiFp(this.configuration).meteoraDlmmTxDepositPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Return Solana instructions that create a position and deposit to Meteora via Hawksight.
     * @param {TxInitializeBinArraysBody} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MeteoraDLMMInstructionsApi
     */
    public async meteoraDlmmTxInitializeBinArraysPost(body: TxInitializeBinArraysBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<TransactionMetadata>> {
        return MeteoraDLMMInstructionsApiFp(this.configuration).meteoraDlmmTxInitializeBinArraysPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Return Solana instructions that create a position and deposit to Meteora via Hawksight.
     * @param {TxWithdrawBody} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MeteoraDLMMInstructionsApi
     */
    public async meteoraDlmmTxWithdrawPost(body: TxWithdrawBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<TransactionMetadata>> {
        return MeteoraDLMMInstructionsApiFp(this.configuration).meteoraDlmmTxWithdrawPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
