/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Detailed information about token B in the pool.
 *
 * @export
 * @interface OrcautilpoolsTokenB
 */
export interface OrcautilpoolsTokenB {

    /**
     * Mint address for token B.
     *
     * @type {string}
     * @memberof OrcautilpoolsTokenB
     */
    mint?: string;

    /**
     * Symbol for token B.
     *
     * @type {string}
     * @memberof OrcautilpoolsTokenB
     */
    symbol?: string;

    /**
     * Full name of token B.
     *
     * @type {string}
     * @memberof OrcautilpoolsTokenB
     */
    name?: string;

    /**
     * Number of decimals used by token B.
     *
     * @type {number}
     * @memberof OrcautilpoolsTokenB
     */
    decimals?: number;

    /**
     * URI to the token logo.
     *
     * @type {string}
     * @memberof OrcautilpoolsTokenB
     */
    logoURI?: string;

    /**
     * CoinGecko identifier for the token.
     *
     * @type {string}
     * @memberof OrcautilpoolsTokenB
     */
    coingeckoId?: string;

    /**
     * Indicates if token B is whitelisted.
     *
     * @type {boolean}
     * @memberof OrcautilpoolsTokenB
     */
    whitelisted?: boolean;

    /**
     * Indicates if token B is a pool token.
     *
     * @type {boolean}
     * @memberof OrcautilpoolsTokenB
     */
    poolToken?: boolean;
}
