/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Monthly price range.
 *
 * @export
 * @interface OrcautilpoolsPriceRangeMonth
 */
export interface OrcautilpoolsPriceRangeMonth {

    /**
     * Minimum price of the month.
     *
     * @type {number}
     * @memberof OrcautilpoolsPriceRangeMonth
     */
    min?: number;

    /**
     * Maximum price of the month.
     *
     * @type {number}
     * @memberof OrcautilpoolsPriceRangeMonth
     */
    max?: number;
}
