/* tslint:disable */
/* eslint-disable */
/**
 * Hawksight API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface RegisterBody
 */
export interface RegisterBody {

    /**
     * Transaction priority level, affects the processing speed and fee.
     *
     * @type {string}
     * @memberof RegisterBody
     */
    priority?: RegisterBodyPriorityEnum;

    /**
     * Maximum amount of lamports that can be used as a priority fee.
     *
     * @type {number}
     * @memberof RegisterBody
     */
    maxPriorityFee?: number;

    /**
     * The wallet address of the user to be registered.
     *
     * @type {string}
     * @memberof RegisterBody
     */
    userWallet?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum RegisterBodyPriorityEnum {
    Default = 'Default',
    Low = 'Low',
    Medium = 'Medium',
    High = 'High',
    VeryHigh = 'VeryHigh',
    UnsafeMax = 'UnsafeMax',
    None = 'None'
}

