name: Publish hawk-sdk to npm

on:
  push:
    branches:
      - main # Change if needed
  workflow_dispatch: # Allows manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'
          scope: '@your-scope' # Change if using scoped packages

      - name: Install dependencies
        run: |
          cd hawk-sdk
          yarn install --frozen-lockfile

      - name: Build package (if needed)
        run: |
          cd hawk-sdk
          yarn build # Remove this step if not required

      - name: Publish package
        run: |
          cd hawk-sdk
          yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}